// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Chalk from "chalk";
import * as Process from "process";
import * as Commander from "commander";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

function getArguments(param) {
  var program = new Commander.Command().version("0.0.1").parse(Process.argv);
  var options = program.opts();
  var fileArg = Caml_array.get(program.args, 0);
  var fileToMove = fileArg !== undefined ? Path.resolve(fileArg) : (console.log(Chalk.red("No file specified. Please provide a file name to move")), Process.exit(1));
  var destinationPath = Path.join(Process.cwd(), options.dest);
  return {
          destinationPath: destinationPath,
          fileToMove: fileToMove
        };
}

export {
  getArguments ,
  
}
/* path Not a pure module */
