// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Chalk from "chalk";

function confirm(param) {
  return new Promise((function (resolve, param) {
                process.stdout.write("\n" + Chalk.bold.yellow("WARNING"));
                process.stdout.write("\n" + Chalk.bold.cyan("Move files?") + " [Y/n] ");
                process.stdin.resume();
                process.stdin.setEncoding("utf8");
                process.stdin.on("data", (function (data) {
                        var asString = data.toString().toLowerCase().trim();
                        if (asString === "n") {
                          return resolve(false);
                        } else {
                          return resolve(true);
                        }
                      }));
                
              }));
}

export {
  confirm ,
  
}
/* chalk Not a pure module */
