// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Commondir from "commondir";

function determineDestinationPathKeepingFolderStructure(destinationFolder, fileFullPath) {
  var commonPath = Commondir([
        destinationFolder,
        fileFullPath
      ]);
  return Path.join(destinationFolder, fileFullPath.replace(commonPath, "./"));
}

export {
  determineDestinationPathKeepingFolderStructure ,
  
}
/* path Not a pure module */
