// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Chalk from "chalk";
import * as Commondir from "commondir";

function logFileMove(source, destination) {
  var commonPath = Commondir([
        source,
        destination
      ]);
  var src = Chalk.blue(source.replace(commonPath, ""));
  var dest = Chalk.green(destination.replace(commonPath, ""));
  console.log(src + " " + Chalk.red("=>") + " " + dest);
  
}

export {
  logFileMove ,
  
}
/* chalk Not a pure module */
